manifest:
  remotes:
    - name: zephyrproject-rtos-fork
      url-base: https://github.com/crosscon
  projects:
    - name: zephyr
      remote: zephyrproject-rtos-fork
      revision: UC1_1_VM_PUF
      import: true
  self:
    path: application
